use_gpu: true

# data path
data_path: "pretrain/data/imagenet_vid.pkl"
val_data_path: ""

# model path
init_model_path: "models/rt_mdnet_imagenet.pth"
model_path: "models/rt_mdnet_imagenet.pth"

# input size
img_size: 107
padding: 1.2
padding_ratio: 5.0

# batch size
batch_frames: 8
batch_pos: 64
batch_neg: 196
batch_accum: 50

# training examples sampling
trans_pos: 0.1
scale_pos: 1.3
trans_neg: 2
scale_neg: 1.6
overlap_pos: [0.7, 1]
overlap_neg: [0, 0.5]

# augmentation
flip: True
rotate: 30
blur: 7

# training
lr: 0.0001
grad_clip: 10
lr_mult: {"fc": 1}
ft_layers: ["conv", "fc"]
n_cycles: 1000
cross_val_k: 0
error_threshold: 0.0005
w_decay: 0.0005
momentum: 0.9
frame_interval: 1
adaptive_align: true
seqbatch_size: 50
receptive_field: 75.0
